# Generated by Django 5.1.7 on 2025-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='code_language',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('java', 'Java'), ('javascript', 'JavaScript'), ('bash', 'Bash'), ('c', 'C'), ('cpp', 'C++'), ('ruby', 'Ruby'), ('go', 'Go'), ('php', 'PHP')], max_length=20, null=True),
        ),
    ]
