# Generated by Django 5.1.7 on 2025-03-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_created_by_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog_covers/'),
        ),
    ]
