# Generated by Django 5.1.7 on 2025-03-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
