# Generated by Django 5.1.7 on 2025-03-21 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blog_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogcontent',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
